name: Python Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MPI system dependencies
        run: |
          sudo apt update
          sudo apt install -y -q mpich libmpich-dev
      - name: Install dependencies from pyproject
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
      - name: Run unit tests
        run: |
          python -m pytest tests --maxfail=1 -q
